import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { World } from './world.js';
import { icon,hydrateIcons } from './icons.js';
import { Tutorial } from './tutorial.js';
import { MobileControls } from './mobile.js';
import { ROOMS,OBJECTS,SAVE_KEY,newGame,sanitizeSave,clamp,evaluateRoom,completeRoom,isUnlocked,controlsReady,kitchenDistances } from './rules.js';

const $=id=>document.getElementById(id);
hydrateIcons();
let state;
try{state=sanitizeSave(JSON.parse(localStorage.getItem(SAVE_KEY)));}catch{state=newGame();}
let world,selected=null,tool='inspect',result,focus=null,toastTimer,saveTimer,busy=false,drag=null,joystick={x:0,y:0},keys=new Set(),audioContext=null,savedCamera=null;
let vrSelected=null,vrMessage='Arahkan laser ke objek. Trigger: inspeksi.',vrDirty=true,vrSession=null;
let mobile=null,modalPending=false;
let tutorial=null,returnRoom=0,releasingPointer=false,hadPointerLock=false,tutorialDistance=0,tutorialLook=0;
const coarse=matchMedia('(pointer:coarse)').matches;
const room=()=>ROOMS[state.current];
const values=()=>state.rooms[room().id];
const defFor=id=>OBJECTS[room().id].find(d=>d.id===id)||world?.propDefinitions.get(id);
const colorFor=score=>score>=80?'var(--green)':score>=50?'var(--yellow)':'var(--red)';
const escapeHTML=text=>String(text).replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));
const number=(n,unit)=>`${Number(n).toLocaleString('id-ID',{maximumFractionDigits:1})}${unit==='°'?'':' '}${unit||''}`;
function toast(message){$('toast').querySelector('span').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500);vrMessage=message;vrDirty=true;}
function save(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));}catch{toast('Penyimpanan browser tidak tersedia. Progres sesi ini tetap bisa dimainkan.');}},150);}
function sound(success=false){if(!state.settings.sound)return;try{audioContext??=new AudioContext();if(audioContext.state==='suspended')audioContext.resume();const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.connect(gain);gain.connect(audioContext.destination);osc.type='sine';osc.frequency.setValueAtTime(success?620:430,audioContext.currentTime);osc.frequency.exponentialRampToValueAtTime(success?930:530,audioContext.currentTime+.12);gain.gain.setValueAtTime(.035,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.22);osc.start();osc.stop(audioContext.currentTime+.23);}catch{/* Sound is optional. */}}
function releasePointer(){if(document.pointerLockElement){releasingPointer=true;document.exitPointerLock();}keys.clear();joystick.x=joystick.y=0;mobile?.reset();}
function inputBlocked(){return !!selected||$('modal').open||modalPending||busy||mobile?.portrait||$('mission-panel').classList.contains('mobile-open');}
function modal(html,kind=''){releasePointer();$('modal').dataset.kind=kind;$('modal-content').innerHTML=html;if(mobile?.portrait)modalPending=true;else if(!$('modal').open)$('modal').showModal();}
function closeModal(){if($('modal').dataset.kind==='welcome'){state.onboarding.skipped=true;save();}$('modal').dataset.kind='';modalPending=false;$('modal').close();}
function scoreUI(){
 const previous=result;result=evaluateRoom(room().id,values());$('score').textContent=result.score;$('score-circle').style.strokeDashoffset=270.18*(1-result.score/100);document.documentElement.style.setProperty('--score-color',colorFor(result.score));$('score-status').textContent=result.score>=80?'Ergonomi baik':result.score>=50?'Cukup nyaman':'Perlu perbaikan';$('score-feedback').innerHTML=result.score>=80?'Perubahan kecil.<br>Dampak yang terasa.':result.score>=50?'Sudah lebih baik.<br>Lanjutkan penataan.':'Ruang yang nyaman<br>dimulai dari sini.';
 $('mission-count').textContent=`${result.done} / ${result.tasks.length}`;$('mission-progress').style.width=result.done/result.tasks.length*100+'%';
 $('mission-list').innerHTML=OBJECTS[room().id].map((d,i)=>`<button class="mission-item ${result.tasks[i].done?'done':''} ${selected===d.id?'selected':''}" data-object="${d.id}" aria-label="${d.mission}"><span class="mission-check">${icon('check')}</span><span class="mission-info"><b>${d.mission}</b><small>${result.tasks[i].done?'Sesuai · '+Math.round(result.tasks[i].quality*100)+'%':d.subtitle}</small></span>${icon('chevron')}</button>`).join('');
 $('metrics').innerHTML=result.metrics.map((m,i)=>`<div class="metric-row"><span>${icon(['posture','ruler','sun'][i])}${room().metrics[i]}</span><div class="metric-track"><i style="width:${m}%;background:${colorFor(m)}"></i></div><b>${m}%</b></div>`).join('');
 $('submit-project').disabled=!result.canComplete;$('completion-hint').textContent=result.canComplete?'Siap diaudit · klaim hasil proyek Anda':'Selesaikan semua misi & raih skor ≥ 80';
 $('xp').textContent=state.xp.toLocaleString('id-ID');$('career-level').textContent=`LV. ${String(state.completed.length+1).padStart(2,'0')}`;$('career-label').textContent=state.completed.length?`${state.completed.length} ruang lebih nyaman. Terus bertumbuh.`:'Ruang pertama, langkah pertama.';
 if(previous&&previous.done<result.done){sound(true);toast('Misi tercapai! Ruangan Anda semakin nyaman.');}
 document.querySelectorAll('.world-label').forEach(el=>{const task=result.tasks.find(t=>t.id===el.dataset.object);el.classList.toggle('done',task?.done);const value=el.querySelector('span');if(value)value.textContent=task?.done?'Sesuai':'Periksa';});
 if(selected)feedbackUI();vrDirty=true;
}
function mapUI(){const completed=state.completed.length;$('room-map').innerHTML=ROOMS.map((r,i)=>`<button class="map-room ${i===state.current?'current':''} ${state.completed.includes(r.id)?'complete':''}" data-room="${i}" ${isUnlocked(state,i)?'':'disabled'} title="${isUnlocked(state,i)?r.name:'Selesaikan proyek sebelumnya'}">${icon(isUnlocked(state,i)?r.icon:'lock')} ${r.short}</button>`).join('');$('map-current').textContent=room().name;$('map-progress').textContent=`${completed} / ${ROOMS.length} selesai`;}
function buildLabels(){const ids=room().id==='office'?['chair','monitor','lamp']:room().id==='kitchen'?['counter','fridge','shelf']:room().id==='home'?['broom','mop','box']:room().id==='outdoor'?['carry','planter','path']:['bench','tools','lamp'];$('world-labels').innerHTML=ids.map(id=>`<button class="world-label" data-object="${id}"><i class="label-dot"></i>${defFor(id).name}<span>Periksa</span></button>`).join('');}
function loadRoom(index){
 if(!isUnlocked(state,index)){toast('Selesaikan proyek sebelumnya untuk membuka ruangan ini.');return false;}
 if(busy){toast('Tunggu latihan selesai sebelum berpindah ruangan.');return false;}
 if(world.mover.active){toast('Letakkan atau batalkan barang sebelum berpindah ruangan.');return false;}
 if(world.carrying){toast('Letakkan kotak di meja tujuan atau batalkan bawaan sebelum berpindah.');return false;}
 closeInspector();releasePointer();closeModal();state.current=index;selected=null;focus=null;result=null;vrSelected=null;state.cooking.on=false;state.placements[room().id]??={};world.build(room().id,values(),state.placements[room().id]);world.cookingVisual?.update(state.cooking);
 if(vrSession){world.rig.position.set(world.camera.position.x,0,world.camera.position.z);world.camera.position.set(0,0,0);world.camera.rotation.set(0,0,0);}
 $('header-number').textContent=String(index+1).padStart(2,'0');$('header-room').textContent=room().name;$('project-count').textContent=`0${index+1} / 0${ROOMS.length}`;$('mission-title').innerHTML=room().title;$('mission-description').textContent=room().description;$('scene-category').textContent=room().category;$('scene-area').innerHTML=room().id==='outdoor'?'TAMAN MENTENG <i>·</i> Rumah & lingkungan':'36 m² <i>·</i> Cahaya natural';$('consultant-tip').textContent=room().tip;$('outdoor-button-label').textContent=room().id==='outdoor'?'Kembali ke rumah':'Ke halaman';$('neighborhood-button').hidden=room().id!=='outdoor';buildLabels();scoreUI();mapUI();save();if(room().id==='outdoor')tutorial?.event('outdoor');return true;
}
function closeInspector(){selected=null;$('inspector').hidden=true;document.body.classList.remove('has-inspector');if(world)world.highlight(null);}
function selectObject(id,guided=false){
 const def=defFor(id);if(!def)return;if(busy){toast('Latihan sedang berlangsung…');return;}if(world.mover.active){toast('Letakkan barang terlebih dahulu.');return;}if(world.carrying){toast('Bawa kotak ke penanda meja taman terlebih dahulu.');return;}
 releasePointer();selected=id;if(guided)world.focus(id);world.highlight(id);$('mission-panel').classList.remove('mobile-open');$('inspector').hidden=false;document.body.classList.add('has-inspector');$('object-icon').innerHTML=icon(def.icon);$('object-name').textContent=def.name;$('object-category').textContent=room().category;$('object-description').textContent=def.description;$('model-tools').hidden=!!def.clean;renderControls();scoreUI();const metadata=world.objects.get(id)?.group.userData;$('model-author').value=metadata?.credit?.author||'';$('model-source').value=metadata?.credit?.source||'';$('model-credit').textContent=metadata?.importName||'Impor bersifat lokal untuk ruangan aktif. Untuk glTF, pilih model, .bin, dan seluruh tekstur bersama-sama.';document.querySelector('.model-credit-fields').hidden=!!def.clean;if(room().id==='office'&&id==='chair')tutorial?.event('inspect');
}
function showObjects(){
 if(busy||world.carrying||world.mover.active){toast('Selesaikan aktivitas atau letakkan barang terlebih dahulu.');return;}
 const objects=[...world.objects.keys()].map(id=>defFor(id)).filter(d=>d&&!d.clean);
 modal(`<div class="eyebrow">TATA RUANG BEBAS</div><h2>Barang di ruangan</h2><p>Pilih barang untuk mendekat, berinteraksi, atau memindahkannya.</p><div class="prop-grid">${objects.map(d=>`<button class="secondary-button" data-prop="${d.id}">${icon(d.icon)}${escapeHTML(d.name)}</button>`).join('')}</div>`);
 document.querySelectorAll('[data-prop]').forEach(button=>button.onclick=()=>{closeModal();selectObject(button.dataset.prop,true);});
}
function beginMove(id){
 if(busy||world.carrying||world.mover.active)return;
 if(state.cooking.on&&['stove','counter'].includes(id)){toast('Matikan kompor terlebih dahulu sebelum memindahkannya.');return;}
 if(!world.mover.begin(id)){toast('Dekati barang sebelum mengangkatnya.');return;}
 closeInspector();releasePointer();toast(coarse?'Barang dipegang. Gunakan joystick dan cari tempat kosong, lalu tekan Letakkan. Tersedia tombol Putar dan Batal.':'Barang dipegang. Cari tempat kosong, R untuk putar, F untuk letakkan, X untuk batal.');
}
function placeObject(){
 if(!world.mover.finish()){toast('Tempat terhalang. Arahkan ke lantai atau permukaan kosong.');return;}
 save();sound();toast('Barang diletakkan. Posisi tersimpan di browser ini.');
}
function resetObjectPosition(){
 const ids=selected==='desk'?['desk','monitor','keyboard','lamp','desktop-decor']:selected==='bench'?['bench','lamp']:[selected];
 for(const id of ids){world.removePlacement(id);delete world.placements[id];world.updateHitBox(id);}
 world.renderer.shadowMap.needsUpdate=true;world.focus(selected);save();toast('Posisi awal dipulihkan.');
}
function cookingControls(){
 const c=state.cooking,comfortable=values().counter.height>=88&&values().counter.height<=94;
 return `<section class="cooking-card"><div class="eyebrow">AKTIVITAS DAPUR</div><h3>Sup sayur hangat</h3><ol><li class="${comfortable?'done':''}">Atur meja kerja 88–94 cm.</li><li class="${c.handle?'done':''}">Arahkan gagang panci ke samping.</li><li class="${c.stirred?'done':''}">Nyalakan api dan aduk sup.</li><li class="${c.served?'done':''}">Matikan kompor lalu sajikan.</li></ol><div class="cooking-actions"><button data-cook="handle" class="secondary-button">${c.handle?'Gagang aman ✓':'Arahkan gagang'}</button><button data-cook="power" class="secondary-button">${c.on?'Matikan kompor':'Nyalakan kompor'}</button><button data-cook="stir" class="primary-button" ${c.on?'':'disabled'}>${c.stirred?'Aduk lagi':'Aduk sup'}</button><button data-cook="serve" class="secondary-button" ${c.stirred?'':'disabled'}>${c.served?'Sup sudah disajikan ✓':'Matikan & sajikan'}</button></div><p class="control-hint">${c.on?'Api menyala. Jaga badan dekat meja, siku rileks, dan gagang menjauhi jalur berjalan.':c.served?'Latihan selesai. Kompor mati, sup siap dinikmati.':'Perbaiki tinggi meja lewat misi Meja dapur, lalu mulai memasak.'}</p></section>`;
}
async function cook(action){
 if(busy||room().id!=='kitchen'||world.mover.active)return;
 const c=state.cooking;
 if(action==='handle'){c.handle=1;world.hands.perform('reach');}
 if(action==='power'){c.on=!c.on;if(c.on&&c.served){c.served=false;c.stirred=false;}world.hands.perform('press');}
 if(action==='serve'){if(!c.stirred)return;c.on=false;c.served=true;world.hands.perform('reach');sound(true);toast('Sup siap! Kompor dimatikan dan postur kerja tetap nyaman.');}
 if(action==='stir'){
  if(!c.on)return;
  if(values().counter.height<88||values().counter.height>94||!c.handle){toast('Atur meja 88–94 cm dan arahkan gagang panci ke samping terlebih dahulu.');return;}
  busy=true;c.stirring=true;closeInspector();releasePointer();world.focus('stove');const stove=world.objects.get('stove').group,aim=stove.localToWorld(new THREE.Vector3(-.16,.17,-.13)),front=stove.localToWorld(new THREE.Vector3(-.16,0,.68));if(!world.collision(front.x,front.z)){world.camera.position.set(front.x,1.64,front.z);world.camera.lookAt(aim);world.camera.updateMatrixWorld();}world.hands.perform('stir',2.2);world.cookingVisual.update(c);toast('Mengaduk sup. Siku rileks, badan dekat meja…');
  await new Promise(resolve=>setTimeout(resolve,2200));c.stirring=false;c.stirred=true;busy=false;selectObject('stove');
 }
 world.cookingVisual?.update(c);save();if(selected)renderControls();
}
function controlMinimum(c){if(room().id==='office'&&selected==='monitor'){if(c.key==='height')return Math.max(c.min,Math.ceil(values().chair.deskHeight+43.75));if(c.key==='distance')return Math.max(c.min,values().keyboard.reach+11);}return c.min;}
function renderControls(){
 const def=defFor(selected);if(!def)return;const v=values()[selected]||{};let html='';
 if(def.clean){html=`<div class="control-group"><label class="control-label">Kebersihan lantai <output>${v.cleaned.length} / 3 area</output></label><div class="progress-track"><i style="width:${v.cleaned.length/3*100}%"></i></div><p class="control-hint">${room().id==='home'?'Praktikkan menyapu dan mengepel dengan postur sesuai, lalu bersihkan noda terakhir.':'Gunakan alat Bersihkan dan arahkan crosshair ke noda. Tombol di bawah membantu mendekati noda berikutnya.'}</p></div><button id="clean-next" class="primary-button" ${v.cleaned.length===3?'disabled':''}>${icon('brush')}${v.cleaned.length===3?'Lantai sudah bersih':'Bersihkan noda berikutnya'}</button>`;}
 else{
  html=def.controls.map(c=>`<div class="control-group"><label class="control-label" for="control-${c.key}">${c.label}<output id="value-${c.key}">${c.type==='range'?number(v[c.key],c.unit):''}</output></label>${c.type==='range'?`<div class="range-control"><button class="nudge-button" data-nudge="${c.key}" data-delta="${-c.step}" aria-label="Kurangi ${c.label}">−</button><input id="control-${c.key}" data-control="${c.key}" type="range" min="${controlMinimum(c)}" max="${c.max}" step="${c.step}" value="${v[c.key]}" aria-label="${c.label}"><button class="nudge-button" data-nudge="${c.key}" data-delta="${c.step}" aria-label="Tambah ${c.label}">+</button></div><div class="range-ends"><span>${number(controlMinimum(c),c.unit)}</span><span>${number(c.max,c.unit)}</span></div>`:`<div class="choice-buttons">${c.options.map((o,i)=>`<button class="choice-button ${v[c.key]===i?'active':''}" data-choice="${c.key}" data-value="${i}" aria-pressed="${v[c.key]===i}">${o}</button>`).join('')}</div>`}<p class="control-hint">${c.hint}</p></div>`).join('');
  if(def.layout)html+=`<div class="control-group"><label class="control-label">Geser & putar furnitur <output id="rotation-value">${v.rotation||0}°</output></label><div class="layout-buttons">${def.id==='fridge'?'<span class="empty"></span><button data-layout="z" data-delta="-.1" aria-label="Geser ke belakang">↑</button><span class="empty"></span>':''}<button data-layout="x" data-delta="-.1" aria-label="Geser ke kiri">← 10 cm</button><button data-rotate="45" aria-label="Putar furnitur 45 derajat">↻ 45°</button><button data-layout="x" data-delta=".1" aria-label="Geser ke kanan">10 cm →</button>${def.id==='fridge'?'<span class="empty"></span><button data-layout="z" data-delta=".1" aria-label="Geser ke depan">↓</button><span class="empty"></span>':''}</div></div>`;
  if(def.activity){html+=`<div class="posture-diagram" id="posture-diagram"></div><button id="practice-activity" class="primary-button">${icon(def.icon)}<span>${def.activity==='carry'?(v.delivered?'Bawa ulang kotak':'Angkat & bawa kotak'):v.practiced?'Ulangi latihan':'Praktikkan gerakan'}</span></button><p class="control-hint">${def.activity==='carry'?'Pilih postur baik, angkat kotak, lalu berjalan ke meja taman. Tekan F untuk meletakkan saat sudah dekat.':'Latihan dinilai dari postur yang Anda pilih. Atur terlebih dahulu.'}</p>`;}
 }
 if(!def.clean){
  if(selected==='stove'||selected==='counter')html+=cookingControls();
  html+=`<button id="move-object" class="secondary-button">${icon('move')} Angkat / pindahkan</button><p class="control-hint">Bawa dengan WASD atau joystick. Putar dengan R, letakkan dengan F. Bingkai hijau berarti tempat tersedia.</p><button id="reset-object-position" class="reset-button">Kembalikan posisi awal</button>`;
 }
 $('object-controls').innerHTML=html;feedbackUI();
}
function feedbackUI(){
 const def=defFor(selected);if(!def||!result)return;const task=result.tasks.find(t=>t.id===selected),v=values()[selected];if(!task){$('object-badge').textContent=selected==='stove'&&state.cooking.served?'Sup siap':'Bisa dipindah';$('object-badge').style.setProperty('--score-color','var(--green)');$('object-feedback').innerHTML=icon('move')+'<span>Dekatkan barang ke tubuh. Pastikan tempat tujuan kosong dan jalur berjalan tetap lega.</span>';return;}$('object-badge').textContent=task.done?'Sesuai':'Perlu diatur';$('object-badge').style.setProperty('--score-color',colorFor(task.quality*100));
 let text=task.done?'Pengaturan ini sudah sesuai target klien simulasi. Pertahankan kebiasaan baik dan lakukan jeda aktivitas secara berkala.':def.clean?`Masih ada ${3-v.cleaned.length} area yang perlu dibersihkan.`:'Perhatikan target di bawah setiap pengaturan. Skor berubah langsung saat objek disesuaikan.';
 if(room().id==='kitchen'&&selected==='fridge'){const d=kitchenDistances(v);text=`Jarak aktual: kulkas–sink ${d[0].toFixed(1)} m, kulkas–kompor ${d[1].toFixed(1)} m, sink–kompor ${d[2].toFixed(1)} m. Target latihan: setiap sisi 1,2–3,1 m.`;}
 if(def.activity){text=v.practiced?'Latihan selesai. Gunakan teknik ini setiap kali melakukan aktivitas.':controlsReady(def,v)?'Postur sudah sesuai. Tekan “Praktikkan gerakan” untuk menyelesaikan latihan.':'Perbaiki panjang gagang dan/atau postur terlebih dahulu. Latihan dengan postur berisiko tidak menyelesaikan misi.';const posture=$('posture-diagram');if(posture){const good=v.posture===1;posture.innerHTML=`<svg viewBox="0 0 100 100" aria-label="${good?'Postur netral':'Postur membungkuk'}"><path d="M10 90h80" stroke="#637656"/><g fill="none" stroke="${good?'#d5eca0':'#e5a389'}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round">${good?'<circle cx="45" cy="16" r="7"/><path d="m45 25-3 32 15 13-7 20M42 57 28 74l-5 16M44 34l18 15 15-7"/>':'<circle cx="66" cy="35" r="7"/><path d="m59 39-23 14 8 21-4 16M36 53l-9 20 2 17m21-45 11 17 13 9"/>'}<path d="m77 36 5 52" stroke="#a4b38a" stroke-width="2"/></g></svg><p>${good?'Punggung netral.<br>Beban dekat tubuh.<br>Gerakkan kaki mengikuti aktivitas.':'Punggung membungkuk.<br>Jangkauan terlalu jauh.<br>Pilih postur yang lebih nyaman.'}</p>`;}}
 $('object-feedback').innerHTML=icon(task.done?'check-circle':'bulb')+`<span>${text}</span>`;
 if(def.activity==='carry')$('object-feedback').innerHTML=icon(v.delivered?'check-circle':'box')+`<span>${v.delivered?'Kotak sudah tiba di meja taman. Postur dan perjalanan membawa barang selesai.':controlsReady(def,v)?'Siap diangkat. Setelah menekan tombol, berjalanlah menuju penanda hijau meja taman. Tekan F saat jarak sudah dekat.':'Pilih posisi beban dekat tubuh sebelum mengangkat. Misi baru selesai setelah kotak sampai di meja taman.'}</span>`;
}
function changeValue(key,value){
 if(!selected||busy)return;const def=defFor(selected),c=def.controls?.find(c=>c.key===key);if(!c)return;const v=values()[selected],next=c.type==='range'?clamp(Math.round(value/c.step)*c.step,c.min,c.max):clamp(value,0,c.options.length-1);
 if(def.layout&&!world.canPlace(selected,{...v,[key]:next})){const input=$('control-'+key);if(input)input.value=v[key];toast('Posisi terhalang furnitur atau dinding. Pilih ruang yang masih kosong.');return;}
 world.hands.perform('press');v[key]=Number(next.toFixed(3));if(def.activity){v.practiced=false;if(def.activity==='carry')v.delivered=false;}world.update(selected,v);const input=$('control-'+key);if(input)input.value=v[key];const out=$('value-'+key);if(out&&c.type==='range')out.textContent=number(v[key],c.unit);document.querySelectorAll(`[data-choice="${key}"]`).forEach(b=>{const active=+b.dataset.value===v[key];b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});scoreUI();save();if(room().id==='office'&&selected==='chair'&&controlsReady(def,v))tutorial?.event('adjust');
}
async function practice(id=selected){
 const def=defFor(id),v=values()[id];if(!def?.activity||busy)return;if(!controlsReady(def,v)){toast('Postur belum sesuai. Perbaiki pengaturan sebelum berlatih.');sound();return;}
 if(def.activity==='carry'){closeInspector();const entry=world.objects.get('carry'),position=entry.group.position.clone();world.removePlacement('carry');delete world.placements.carry;entry.group.position.copy(position);v.practiced=false;v.delivered=false;if(!world.beginCarry()){toast('Dekati kotak sebelum mengangkatnya.');return;}toast('Kotak dibawa dekat tubuh. Berjalan ke meja bertanda hijau, lalu tekan F.');scoreUI();save();return;}
 busy=true;world.hands.perform('reach',1.6);const projectId=room().id;toast(def.activity==='lift'?'Tekuk lutut, dekatkan beban, lalu berdiri perlahan…':'Punggung netral. Gerakkan kaki mengikuti arah alat…');world.animateActivity(id);const btn=$('practice-activity');if(btn){btn.disabled=true;btn.textContent='Latihan berlangsung…';}
 await new Promise(resolve=>setTimeout(resolve,1650));if(room().id!==projectId){busy=false;return;}v.practiced=true;if(id==='broom'&&!values().dirt.cleaned.includes(0))values().dirt.cleaned.push(0);if(id==='mop'&&!values().dirt.cleaned.includes(1))values().dirt.cleaned.push(1);world.update(id,v);world.update('dirt',values().dirt);busy=false;scoreUI();save();if(selected===id)renderControls();toast('Gerakan selesai. Postur dan teknik sesuai target latihan.');
}
async function clean(index,guided=false){
 if(busy)return;if(world.carrying){toast('Letakkan kotak terlebih dahulu agar tangan bebas untuk membersihkan.');return;}if(values().dirt.cleaned.includes(index))return;
 if(room().id==='home'&&(!values().broom.practiced||!values().mop.practiced)){toast('Selesaikan latihan Sapu dan Pel dengan postur baik terlebih dahulu.');return;}
 if(tool!=='clean'){setTool('clean',false);}
 const d=world.dirts[index];if(guided){world.objects.get('dirt').group=d;world.focus('dirt');}busy=true;world.hands.perform('clean',.7);const projectId=room().id;toast('Membersihkan area…');const baseScale=d.scale.clone();const start=performance.now();
 await new Promise(resolve=>{function step(){const t=clamp((performance.now()-start)/700,0,1);d.scale.copy(baseScale).multiplyScalar(1-t*.9);if(t<1)requestAnimationFrame(step);else resolve();}requestAnimationFrame(step);});
 if(projectId!==room().id){busy=false;return;}values().dirt.cleaned.push(index);d.scale.copy(baseScale);world.update('dirt',values().dirt);busy=false;scoreUI();save();if(selected==='dirt')renderControls();toast(`Area bersih · ${values().dirt.cleaned.length} dari 3 noda selesai.`);tutorial?.event('clean');
}
function setTool(next,announce=true){tool=next;document.querySelectorAll('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));const hints={inspect:'Inspeksi: arahkan ke objek lalu tekan F, atau klik misi untuk mendekat.',adjust:'Sesuaikan: pilih furnitur untuk mengubah pengaturannya.',clean:'Bersihkan: arahkan crosshair ke noda dan tekan F.',layout:'Tata ruang: pilih furnitur bertanda geser untuk mengatur posisinya.'};if(announce){sound();toast(hints[next]);}if(selected&&next==='clean')selectObject('dirt');else if(selected&&next==='layout')renderControls();}

function interact(hit=world.pick()){
 if($('modal').open||busy)return;if(world.mover.active){placeObject();return;}if(hit?.id==='gate'){if(world.carrying){toast('Letakkan kotak agar tangan bebas untuk membuka gerbang.');return;}operateGate();return;}if(world.carrying){deliverCarry();return;}if(hit?.id==='exit'||hit?.id==='entrance'){usePortal();return;}if(!hit){toast('Dekati objek (maks. 3,5 m), lalu arahkan titik tengah layar.');return;}
 if(hit.id==='dirt'&&tool==='clean'){clean(hit.dirtIndex);return;}
 if(tool==='layout'&&hit.id!=='dirt'){beginMove(hit.id);return;}
 selectObject(hit.id);
}
async function startExplore(){closeInspector();$('mission-panel').classList.remove('mobile-open');if(coarse)return;try{await world.renderer.domElement.requestPointerLock();}catch{toast('Klik dan seret ruangan untuk melihat sekitar; WASD tetap bisa digunakan.');}}
function guideDoor(){if(busy||world.carrying||world.mover.active){toast('Selesaikan aktivitas atau letakkan kotak terlebih dahulu.');return;}closeInspector();releasePointer();world.focus(room().id==='outdoor'?'entrance':'exit');toast('Pintu sudah di depan Anda. Arahkan crosshair dan tekan F untuk berpindah.');}
function guideNeighborhood(){if(room().id!=='outdoor'||busy||world.carrying||world.mover.active){toast('Selesaikan aktivitas atau letakkan kotak terlebih dahulu.');return;}closeInspector();releasePointer();world.focus('gate');toast('Tekan F pada gerbang atau panelnya. Setelah terbuka, berjalanlah ke jalan dan rumah tetangga. Shift untuk berlari.');}
function operateGate(){if(!world.toggleGate()){toast('Mundur dari jalur gerbang sebelum menutupnya.');return;}world.hands.perform('press');sound();toast(world.gate.target?'Gerbang dibuka. Selamat menjelajahi Taman Menteng.':'Gerbang ditutup. Tekan F pada panel untuk membukanya kembali.');}
function usePortal(){world.hands.perform('reach');if(room().id==='outdoor'){loadRoom(returnRoom);}else{returnRoom=state.current;loadRoom(ROOMS.findIndex(r=>r.id==='outdoor'));}if(vrSession)placeVRPanel();}
function deliverCarry(){if(!world.carrying)return;if(!world.finishCarry()){toast('Belum sampai. Dekati meja taman bertanda hijau untuk meletakkan kotak.');return;}values().carry.practiced=true;values().carry.delivered=true;world.update('carry',values().carry);$('carry-hud').hidden=true;scoreUI();save();sound(true);toast('Kotak sampai di meja taman. Beban dibawa dekat tubuh dan jalur dilalui dengan aman.');}
function cancelCarry(){world.cancelCarry();$('carry-hud').hidden=true;toast('Kotak dikembalikan ke tempat awal. Misi membawa barang belum selesai.');}
function startTutorial(){if(busy||world.carrying||world.mover.active){toast('Selesaikan aktivitas yang sedang berlangsung terlebih dahulu.');return;}loadRoom(0);closeModal();tutorialDistance=0;tutorialLook=0;tutorial.start();}
function welcome(){modal(`<div class="welcome-brand">${icon('brand')}<span>ergo<b>flip</b></span><small>THE ERGONOMICS SIMULATOR</small></div><span class="eyebrow">RUANG LEBIH BAIK. HIDUP LEBIH NYAMAN.</span><h2>Setiap perubahan kecil,<br>dimulai dari Anda.</h2><p>Jadilah konsultan ergonomi. Jelajahi rumah dan halaman, atur furnitur, lalu bantu klien bergerak dan bekerja lebih nyaman.</p><div class="welcome-route"><span>${icon('office')}Kantor</span><i>→</i><span>${icon('kitchen')}Dapur</span><i>→</i><span>${icon('home')}Rumah</span><i>→</i><span>${icon('sun')}Halaman</span></div><div class="welcome-controls"><span><kbd>WASD</kbd>Bergerak</span><span>${icon('mouse')}Melihat</span><span><kbd>F</kbd>Interaksi</span><span><kbd>Esc</kbd>Menu</span></div><p class="welcome-goal">Arahkan <b>crosshair</b> ke objek → perbaiki pengaturan → selesaikan misi dengan skor <b>≥ 80</b>. Di mobile, gunakan joystick dan tombol F.</p><div class="welcome-actions"><button id="play-tutorial" class="primary-button">${icon('bulb')}Main Tutorial <small>6 langkah interaktif</small></button><button id="skip-tutorial" class="secondary-button">Langsung Main ${icon('arrow-right')}</button></div><small class="welcome-note">Tutorial bisa diulang dari menu. Progres permainan tersimpan otomatis.</small>`,'welcome');$('play-tutorial').onclick=()=>{$('modal').dataset.kind='';startTutorial();};$('skip-tutorial').onclick=()=>{state.onboarding.skipped=true;closeModal();save();};}
function pauseMenu(){closeInspector();modal(`<div class="eyebrow">${icon('clipboard')} MENU PERMAINAN</div><h2>Ambil jeda sejenak.</h2><p>${room().name} · skor ${result.score}% · ${state.xp.toLocaleString('id-ID')} XP. Progres Anda tersimpan otomatis.</p><div class="pause-actions"><button id="resume-game" class="primary-button">${icon('move')}Lanjutkan bermain</button><button id="menu-tutorial" class="secondary-button">${icon('bulb')}Main Tutorial</button><button id="menu-help" class="secondary-button">${icon('help')}Cara bermain</button><button id="menu-projects" class="secondary-button">${icon('layout')}Pilih proyek</button><button id="menu-settings" class="secondary-button">${icon('settings')}Grafis & kontrol</button><button id="menu-assets" class="secondary-button">${icon('box')}Model 3D & sumber aset</button></div><p class="menu-controls">WASD berjalan · Mouse melihat · F berinteraksi dengan target crosshair · Esc membuka menu.</p>`,'pause');$('resume-game').onclick=()=>{closeModal();};$('menu-tutorial').onclick=startTutorial;$('menu-help').onclick=help;$('menu-projects').onclick=showProjects;$('menu-settings').onclick=settings;$('menu-assets').onclick=assetLibrary;}
function assetLibrary(){modal(`<div class="eyebrow">PUSTAKA MODEL 3D</div><h2>Detail yang Anda pilih.</h2><p>Model Sketchfab Anda sudah terpasang: tiga jenis pohon di taman dan lingkungan rumah, kabinet serta lampu dapur Scandinavian, dan kulkas, mesin kopi, serta sofa dari Modern Apartment. Tangan pemain memakai Female hand karya deep3dstudio, dengan pasangan kanan/kiri dan animasi jari.</p><p>Pilih furnitur di ruangan lalu gunakan <b>Impor model</b> untuk memasang GLB atau paket glTF lokal. Model asli tetap tersedia jika berkas tidak valid.</p><div class="asset-links"><a href="https://sketchfab.com/search?type=models&features=downloadable&q=office%20chair" target="_blank" rel="noopener">Kursi & meja kantor ${icon('arrow-right')}</a><a href="https://sketchfab.com/search?type=models&features=downloadable&q=kitchen" target="_blank" rel="noopener">Peralatan dapur ${icon('arrow-right')}</a><a href="https://sketchfab.com/search?type=models&features=downloadable&q=garden" target="_blank" rel="noopener">Taman & furnitur outdoor ${icon('arrow-right')}</a></div><p>Unduhan Sketchfab memerlukan akun dan lisensi yang sesuai. Simpan nama kreator serta tautan model untuk atribusi. Game tidak mengambil aset dari viewer tanpa izin.</p><p><a href="/assets/CREDITS.md" target="_blank" rel="noopener">Lihat sumber dan lisensi aset bawaan</a></p><button class="primary-button" id="close-library">Kembali bermain</button>`);$('close-library').onclick=closeModal;}
function finishProject(){if(busy)return;const completed=completeRoom(state);if(!completed.ok){toast('Selesaikan seluruh misi dan capai skor minimal 80.');return;}closeInspector();scoreUI();mapUI();save();sound(true);if(vrSession){vrMessage=`Proyek selesai! +${completed.reward} XP. Pilih Lanjut di panel.`;vrDirty=true;return;}
 const nextIndex=ROOMS.findIndex((r,i)=>!state.completed.includes(r.id)&&isUnlocked(state,i)),last=state.completed.length===ROOMS.length;modal(`<div class="eyebrow">${icon('badge')} ${last?'SELURUH PROYEK SELESAI':'PROYEK SELESAI'}</div><h2>${last?'Ruang yang lebih baik.<br>Dimulai dari Anda.':'Perubahan Anda<br>membuat perbedaan.'}</h2><p>${room().name} kini lebih mendukung kenyamanan klien. ${last?'Anda telah menyelesaikan seluruh proyek rumah, halaman, dan studio.':'Lanjutkan perjalanan ke proyek yang tersedia.'}</p><div class="result-score"><strong>${completed.score}</strong><div><small>SKOR ERGONOMI / 100</small><p>Semua misi terselesaikan</p><p style="color:var(--lime)">+${completed.reward} XP ${completed.reward?'· Reward proyek':'· Reward sudah diklaim'}</p></div></div><p>Skor awal ${evaluateRoom(room().id,newGame().rooms[room().id]).score}% → skor akhir ${completed.score}%. Progres tersimpan otomatis di browser ini.</p><button class="primary-button" id="next-project">${nextIndex<0?'Lihat perjalanan Anda':'Lanjut ke '+ROOMS[nextIndex].name} ${icon('arrow-right')}</button>`);$('next-project').onclick=()=>nextIndex<0?showProjects():loadRoom(nextIndex);
}
function showProjects(){modal(`<div class="eyebrow">PERJALANAN KONSULTAN</div><h2>Rumah dan halaman.<br>Satu perubahan baik.</h2><p>Halaman bebas dijelajahi sejak awal. Selesaikan kantor, dapur, rumah, dan halaman untuk membuka studio bonus. Mode desktop, mobile, dan VR berbagi progres yang sama.</p>${ROOMS.map((r,i)=>`<button class="project-card" data-project="${i}" ${isUnlocked(state,i)?'':'disabled'}><span>0${i+1}</span><div><b>${r.name}${r.id==='workshop'?' · BONUS':''}</b><small>${state.completed.includes(r.id)?`Selesai · skor terbaik ${state.best[r.id]}%`:isUnlocked(state,i)?`${r.reward} XP · 5 misi`:'Terkunci · selesaikan proyek sebelumnya'}</small></div>${icon(isUnlocked(state,i)?'arrow-right':'lock')}</button>`).join('')}`);document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>loadRoom(+b.dataset.project));}
function help(){
 modal(`<div class="eyebrow">CARA BERMAIN ERGOFLIP</div><h2>Lihat. Sesuaikan.<br>Rasakan perubahannya.</h2><p>Anda adalah konsultan ergonomi. Mulai dari objek yang perlu diperbaiki, ikuti target klien, lalu selesaikan lima misi di setiap area.</p>
 <div class="help-grid"><div><kbd>WASD</kbd><span>Bergerak<small>Berjalan di rumah dan halaman</small></span></div><div>${icon('mouse')}<span>Mouse untuk melihat<small>Klik Jelajahi / seret layar</small></span></div><div><kbd>F</kbd><span>Interaksi<small>Dekati objek hingga ≤ 3,5 m</small></span></div><div>${icon('scan')}<span>Crosshair = target<small>Nama objek muncul saat terarah</small></span></div><div><kbd>Esc</kbd><span>Menu permainan<small>Panduan, tutorial, grafis, proyek</small></span></div><div><kbd>1–4</kbd><span>Pilih peralatan<small>Inspeksi, atur, bersih, tata</small></span></div></div>
 <p><b>Jalur cepat:</b> klik misi atau penanda untuk mendekati objek dan membuka pengaturan. <b>Mobile:</b> joystick kiri untuk berjalan, usap ruangan untuk melihat, tombol F untuk interaksi. Ikon clipboard membuka daftar misi.</p>
 <p><b>Outdoor:</b> tekan F pada pintu keluar. Saat membawa kotak, berjalan ke meja taman bertanda hijau lalu tekan F dalam jarak 1,8 m. Halaman tersedia sejak awal. <b>Lingkungan Menteng:</b> klik Jelajahi lingkungan untuk mendekati gerbang, lalu F untuk membukanya. Berjalan keluar menuju jalan dan lima rumah tetangga. Tahan Shift untuk berlari di luar; Kembali ke rumah membantu menemukan pintu masuk.</p>
 <p><b>Tujuan:</b> selesaikan semua misi dan capai skor ≥ 80. Hijau ≥ 80, kuning 50–79, merah &lt; 50. Reward hanya sekali per proyek; progres tersimpan otomatis.</p>
 <p><b>Profil klien:</b> tinggi 170 cm, lipat lutut 46 cm, siku berdiri 102 cm, mata duduk 120 cm. Target angka disederhanakan untuk latihan.</p>
 <p>Sumber pembelajaran: <a href="https://www.osha.gov/etools/computer-workstations" target="_blank" rel="noopener">OSHA — Computer Workstations</a> dan <a href="https://www.hse.gov.uk/msd/manual-handling/good-handling-technique.htm" target="_blank" rel="noopener">HSE — Teknik mengangkat</a>.</p><button id="start-help" class="primary-button">Siap bermain ${icon('arrow-right')}</button>`);$('start-help').onclick=closeModal;
}
function settings(){modal(`<div class="eyebrow">ATUR PENGALAMAN ANDA</div><h2>Nyaman untuk bermain.</h2><div class="settings-row"><span>Kualitas grafis<small>Otomatis memakai mode ringan di perangkat sentuh</small></span><select id="quality-select" aria-label="Kualitas grafis"><option value="auto">Otomatis</option><option value="high">Tinggi</option><option value="low">Ringan</option></select></div><div class="settings-row"><span>Sensitivitas kamera<small>Sesuaikan kecepatan melihat sekitar</small></span><input type="range" id="sensitivity" aria-label="Sensitivitas kamera" min=".3" max="2" step=".1" value="${state.settings.sensitivity}"></div><div class="settings-row"><span>Penanda objek<small>Tampilkan label bantuan di ruangan</small></span><input type="checkbox" id="labels-toggle" aria-label="Penanda objek" ${state.settings.labels?'checked':''}></div><div class="settings-row"><span>Suara interaksi<small>Nada lembut saat misi tercapai</small></span><input type="checkbox" id="sound-toggle" aria-label="Suara interaksi" ${state.settings.sound?'checked':''}></div><button id="project-list-button" class="secondary-button" style="margin-top:20px">${icon('layout')} Lihat perjalanan proyek</button><button id="reset-progress" class="reset-button">Mulai ulang progres</button><p>Progres disimpan di browser ini. Impor GLB/glTF hanya berlaku selama ruangan aktif dan tidak disimpan.</p>`);$('quality-select').value=state.settings.quality;$('quality-select').onchange=e=>{state.settings.quality=e.target.value;world.setQuality(e.target.value);save();};$('sensitivity').oninput=e=>{state.settings.sensitivity=+e.target.value;save();};$('labels-toggle').onchange=e=>{state.settings.labels=e.target.checked;save();};$('sound-toggle').onchange=e=>{state.settings.sound=e.target.checked;updateSound();save();sound();};$('project-list-button').onclick=showProjects;$('reset-progress').onclick=()=>{modal(`<div class="eyebrow">MULAI PERJALANAN BARU</div><h2>Ulangi dari ruang pertama?</h2><p>Skor, XP, dan progres di browser ini akan dihapus. Pengaturan grafis dan kontrol tetap disimpan.</p><button id="confirm-reset" class="primary-button">Ya, mulai ulang</button><button id="cancel-reset" class="secondary-button" style="margin-top:10px">Kembali ke pengaturan</button>`);$('confirm-reset').onclick=()=>{if(busy){toast('Tunggu aktivitas selesai.');return;}if(world.carrying)cancelCarry();if(tutorial.active)tutorial.finish(false);const preferences={...state.settings,tutorialCompleted:false};state=newGame();state.settings=preferences;returnRoom=0;loadRoom(0);welcome();toast('Perjalanan baru dimulai. Selamat menata!');};$('cancel-reset').onclick=settings;};}
function updateSound(){$('sound-button').innerHTML=icon(state.settings.sound?'volume':'volume-off');$('sound-button').setAttribute('aria-label',state.settings.sound?'Matikan suara':'Aktifkan suara');}

// Local models are decoded in-browser. The built-in object remains on failed imports.
async function importModel(files){
 const pack=Array.from(files||[]),file=pack.find(f=>/\.(glb|gltf)$/i.test(f.name));
 if(!selected)return;
 if(!file){toast('Pilih GLB atau berkas glTF beserta .bin dan teksturnya.');return;}
 const id=selected,project=room().id,entry=world.objects.get(id);
 if(pack.reduce((n,f)=>n+f.size,0)>25*1024*1024){toast('Paket model terlalu besar. Batas total 25 MB.');return;}
 const request=Symbol('model-import');entry.importRequest=request;
 const urls=new Map();let model=null,installed=false,dependencyError=null;
 try{
  toast('Memuat model 3D lokal…');
  for(const part of pack){if(urls.has(part.name))throw new Error('Duplicate asset filenames');urls.set(part.name,URL.createObjectURL(part));}
  const manager=new THREE.LoadingManager();
  manager.setURLModifier(url=>{
   // GLTFLoader creates local blob URLs for images embedded in GLB bufferViews.
   if(url.startsWith('data:')||url.startsWith(`blob:${location.origin}/`))return url;
   const name=decodeURIComponent(url.split('?')[0]).replaceAll('\\','/').split('/').pop();
   if(urls.has(name))return urls.get(name);
   dependencyError=new Error('Missing local glTF dependency: '+name);throw dependencyError;
  });
  manager.onError=url=>{dependencyError??=new Error('Invalid local glTF dependency');};
  const data=/\.gltf$/i.test(file.name)?await file.text():await file.arrayBuffer();
  const gltf=await new GLTFLoader(manager).parseAsync(data,'');model=gltf.scene;
  // GLTFLoader can recover from a missing image with an untextured material.
  // Reject the incomplete import so the previously visible furniture is retained.
  if(dependencyError)throw dependencyError;
  if(project!==room().id||world.objects.get(id)!==entry||entry.importRequest!==request)return;
  const bounds=new THREE.Box3().setFromObject(model),size=bounds.getSize(new THREE.Vector3());
  if(!Number.isFinite(size.length())||size.length()===0)throw new Error('Empty model');
  entry.group.updateWorldMatrix(true,true);
  const target=new THREE.Box3().setFromObject(entry.group).applyMatrix4(entry.group.matrixWorld.clone().invert()),targetSize=target.getSize(new THREE.Vector3());
  const scale=Math.min(targetSize.x/Math.max(size.x,.001),targetSize.y/Math.max(size.y,.001),targetSize.z/Math.max(size.z,.001));
  model.scale.setScalar(scale);
  const center=bounds.getCenter(new THREE.Vector3()).multiplyScalar(scale);
  model.position.set(-center.x,target.min.y-bounds.min.y*scale,-center.z);
  model.userData.importBaseY=model.position.y;
  model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.userData.imported=true;}});
  if(entry.group.userData.importedModel){const old=entry.group.userData.importedModel;entry.group.remove(old);disposeModel(old);}
  entry.group.children.forEach(c=>c.visible=false);
  entry.group.add(model);entry.group.userData.importedModel=model;entry.group.userData.importName=file.name;installed=true;
  world.updateHitBox(id);world.highlight(selected);
  if(selected===id)$('model-credit').textContent=file.name+' · '+($('model-author').value.trim()||'tambahkan nama kreator untuk atribusi');
  toast('Model dimuat. Parameter ergonomi tetap mengikuti objek asli.');
 }catch(error){
  console.warn('Local model import:',error.message);
  toast('Model tidak dapat dimuat. Pilih GLB valid atau seluruh berkas glTF; objek sebelumnya tetap tersedia.');
 }finally{
  if(model&&!installed)disposeModel(model);
  urls.forEach(url=>URL.revokeObjectURL(url));
 }
}
function disposeModel(model){model.traverse(o=>{if(o.isMesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material]){for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose();}}});}

// WebXR: controller laser inspection, a world-space control panel, smooth movement,
// and snap turning. Every room can be completed without the DOM overlay.
const vrControllers=[],vrButtons=[];let vrPanel,vrCanvas,vrTexture,vrTitle,vrLastTurn=0;
function makeVRButton(label,action,y,x=0,width=.76){const canvas=document.createElement('canvas');canvas.width=Math.round(width*700);canvas.height=58;const ctx=canvas.getContext('2d');ctx.fillStyle='#3c503a';ctx.fillRect(0,0,canvas.width,58);ctx.strokeStyle='#72885a';ctx.strokeRect(1,1,canvas.width-2,56);ctx.fillStyle='#e9f1d7';ctx.font='20px sans-serif';ctx.textAlign='center';ctx.fillText(label,canvas.width/2,36,canvas.width-12);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const b=new THREE.Mesh(new THREE.PlaneGeometry(width,.086),new THREE.MeshBasicMaterial({map:texture}));b.position.set(x,y,.003);b.userData.action=action;vrPanel.add(b);vrButtons.push(b);}
function setupVR(){
 vrPanel=new THREE.Group();vrPanel.visible=false;world.scene.add(vrPanel);vrCanvas=document.createElement('canvas');vrCanvas.width=768;vrCanvas.height=512;vrTexture=new THREE.CanvasTexture(vrCanvas);vrTexture.colorSpace=THREE.SRGBColorSpace;vrTitle=new THREE.Mesh(new THREE.PlaneGeometry(.85,.57),new THREE.MeshBasicMaterial({map:vrTexture}));vrTitle.position.y=.31;vrPanel.add(vrTitle);
 for(let i=0;i<2;i++){const c=world.renderer.xr.getController(i);const geo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3(0,0,-3.5)]);const line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:'#d5eca0',transparent:true,opacity:.8}));c.add(line);world.rig.add(c);c.addEventListener('connected',e=>{c.userData.source=e.data;});c.addEventListener('disconnected',()=>{c.userData.source=null;});c.addEventListener('selectstart',()=>{const ray=new THREE.Raycaster();ray.ray.origin.setFromMatrixPosition(c.matrixWorld);ray.ray.direction.set(0,0,-1).applyQuaternion(c.getWorldQuaternion(new THREE.Quaternion()));const hit=ray.intersectObjects(vrButtons);if(hit.length&&hit[0].distance<3){hit[0].object.userData.action();return;}if(world.carrying){deliverCarry();return;}const object=world.pick(undefined,c);if(object){if(object.id==='gate'){operateGate();return;}if(['exit','entrance'].includes(object.id)){usePortal();return;}if(object.id==='dirt'){clean(object.dirtIndex);return;}vrSelected=object.id;vrMessage=defFor(vrSelected)?.description||'';vrDirty=true;}});c.addEventListener('squeezestart',()=>{placeVRPanel();});vrControllers.push(c);}
}
function placeVRPanel(){const cam=world.renderer.xr.getCamera();const pos=cam.getWorldPosition(new THREE.Vector3()),q=cam.getWorldQuaternion(new THREE.Quaternion());const direction=new THREE.Vector3(0,0,-1).applyQuaternion(q);direction.y=0;direction.normalize();vrPanel.position.copy(pos).addScaledVector(direction,1.3);vrPanel.position.y=Math.max(.9,pos.y-.1);vrPanel.lookAt(pos.x,vrPanel.position.y,pos.z);vrDirty=true;}
function wrapCanvas(ctx,text,x,y,width,lineHeight,max=5){const words=text.split(' ');let line='',row=0;for(const word of words){const test=line+word+' ';if(ctx.measureText(test).width>width&&line){ctx.fillText(line,x,y);y+=lineHeight;if(++row>=max)return y;line=word+' ';}else line=test;}ctx.fillText(line,x,y);return y+lineHeight;}
function renderVRPanel(){
 if(!vrDirty||!vrSession)return;vrDirty=false;for(const b of vrButtons){vrPanel.remove(b);b.geometry.dispose();b.material.map.dispose();b.material.dispose();}vrButtons.length=0;const ctx=vrCanvas.getContext('2d');ctx.fillStyle='#202d29';ctx.fillRect(0,0,768,512);ctx.fillStyle='#d5eca0';ctx.font='24px sans-serif';ctx.fillText(`ERGOFLIP / ${room().name.toUpperCase()}`,35,52);ctx.fillStyle='#eff3e9';ctx.font='42px sans-serif';ctx.fillText(`Skor ${result.score}%   |   ${result.done}/5 misi`,35,111);ctx.font='23px sans-serif';ctx.fillStyle='#b7c6aa';wrapCanvas(ctx,vrMessage,35,158,690,30,3);
 let y=.19;const def=defFor(vrSelected);if(def&&!def.clean){ctx.fillStyle='#d5eca0';ctx.font='28px sans-serif';ctx.fillText(def.name,35,293);const v=values()[vrSelected];for(const c of def.controls){const text=c.type==='range'?`${c.label}: ${number(v[c.key],c.unit)}`:`${c.label}: ${c.options[v[c.key]]}`;const adjust=direction=>{const prevSelected=selected;selected=vrSelected;const next=c.type==='range'?v[c.key]+direction*c.step:(v[c.key]+1)%c.options.length;changeValue(c.key,next);selected=prevSelected;vrMessage=c.hint;vrDirty=true;};if(c.type==='range'){makeVRButton('−',()=>adjust(-1),y,-.335,.08);makeVRButton(text,()=>{vrMessage=c.hint;vrDirty=true;},y,0,.56);makeVRButton('+',()=>adjust(1),y,.335,.08);}else makeVRButton(text,()=>adjust(1),y);y-=.105;}
   if(def.activity){makeVRButton('Praktikkan gerakan',()=>practice(vrSelected),y);y-=.105;}
 }
 makeVRButton('Misi berikutnya / dekati objek',()=>{if(world.carrying){toast('Bawa kotak ke meja taman atau batalkan bawaan terlebih dahulu.');return;}const next=result.tasks.find(t=>!t.done&&t.id!==vrSelected)||result.tasks.find(t=>!t.done);if(next){vrSelected=next.id;const pos=world.positionOf(next.id),offset=new THREE.Vector3(1.25,0,1.5);const target=pos.clone().add(offset);if(!world.collision(target.x,target.z))world.rig.position.set(target.x,0,target.z);vrMessage=defFor(next.id).description;}else vrMessage='Semua misi selesai. Audit proyek untuk menerima reward.';placeVRPanel();},y);y-=.105;
 makeVRButton(result.canComplete?'Audit proyek / klaim reward':'Bersihkan noda berikutnya',()=>{if(result.canComplete)finishProject();else{const i=[0,1,2].find(n=>!values().dirt.cleaned.includes(n));if(i!==undefined)clean(i);else toast('Selesaikan pengaturan objek terlebih dahulu.');}},y);y-=.105;
 if(world.carrying){makeVRButton('Letakkan kotak di meja taman',deliverCarry,y);y-=.105;makeVRButton('Batalkan bawaan',cancelCarry,y);y-=.105;}
 makeVRButton(room().id==='outdoor'?'Kembali ke rumah':'Jelajahi halaman',()=>{usePortal();placeVRPanel();},y);y-=.105;
 const nextIndex=ROOMS.findIndex((r,i)=>!state.completed.includes(r.id)&&isUnlocked(state,i));if(state.completed.includes(room().id)&&nextIndex>=0){makeVRButton('Lanjut ke '+ROOMS[nextIndex].name,()=>{loadRoom(nextIndex);placeVRPanel();},y);y-=.105;}
 makeVRButton('Keluar VR',()=>vrSession?.end(),y);vrTexture.needsUpdate=true;
}
async function enterVR(){
 if(busy||world.mover.active){toast('Selesaikan aktivitas atau letakkan barang sebelum masuk VR.');return;}
 releasePointer();closeInspector();if(!window.isSecureContext){modal(`<div class="eyebrow">MODE IMERSIF</div><h2>WebXR memerlukan HTTPS.</h2><p>Buka game dari alamat HTTPS pada browser headset yang mendukung WebXR. Localhost juga didukung untuk pengembangan.</p><p>Di desktop atau ponsel ini, semua misi tetap bisa dimainkan dengan kontrol biasa.</p>`);return;}
 try{if(!navigator.xr||!await navigator.xr.isSessionSupported('immersive-vr')){modal(`<div class="eyebrow">MODE IMERSIF</div><h2>Siap untuk headset Anda.</h2><p>Browser ini belum menyediakan sesi VR. Buka alamat game melalui HTTPS pada browser headset dengan dukungan WebXR.</p><div class="help-grid"><div>${icon('scan')}<span>Trigger<small>Pilih objek / tombol panel</small></span></div><div>${icon('move')}<span>Stik kiri<small>Bergerak perlahan</small></span></div><div>${icon('vr')}<span>Stik kanan<small>Berputar 30°</small></span></div><div>${icon('clipboard')}<span>Grip<small>Panggil panel di depan</small></span></div></div><p>Panel 3D mendukung pengaturan, bersih-bersih, latihan, dan pergantian proyek. Pengujian langsung tetap memerlukan headset fisik.</p>`);return;}
  const session=await navigator.xr.requestSession('immersive-vr',{optionalFeatures:['local-floor','bounded-floor']});savedCamera={position:world.camera.position.clone(),rotation:world.camera.rotation.clone()};world.rig.position.set(world.camera.position.x,0,world.camera.position.z);world.camera.position.set(0,0,0);world.camera.rotation.set(0,0,0);vrSession=session;await world.renderer.xr.setSession(session);vrPanel.visible=true;$('hud').style.visibility='hidden';document.querySelector('.topbar').style.visibility='hidden';session.addEventListener('end',()=>{const position=world.renderer.xr.getCamera().getWorldPosition(new THREE.Vector3());vrSession=null;vrPanel.visible=false;world.rig.position.set(0,0,0);world.rig.rotation.set(0,0,0);world.camera.position.set(position.x,1.64,position.z);world.camera.rotation.copy(savedCamera.rotation);$('hud').style.visibility='';document.querySelector('.topbar').style.visibility='';toast('Kembali ke mode desktop. Progres VR tersimpan.');});setTimeout(placeVRPanel,500);
 }catch(error){console.warn('WebXR:',error.message);toast('Sesi VR tidak dimulai. Periksa izin headset dan koneksi HTTPS.');}
}
function tickVR(dt,time){if(!vrSession)return;for(const c of vrControllers){const source=c.userData.source;if(!source?.gamepad)continue;const axes=source.gamepad.axes,x=axes.length>2?axes[2]:axes[0],y=axes.length>3?axes[3]:axes[1];if(source.handedness==='left'&&(Math.abs(x)>.15||Math.abs(y)>.15)){const cam=world.renderer.xr.getCamera(),q=cam.getWorldQuaternion(new THREE.Quaternion()),forward=new THREE.Vector3(0,0,-1).applyQuaternion(q);forward.y=0;forward.normalize();const right=new THREE.Vector3().crossVectors(forward,new THREE.Vector3(0,1,0));const delta=forward.multiplyScalar(-y*dt*1.25).addScaledVector(right,x*dt*1.25);const pos=cam.getWorldPosition(new THREE.Vector3());if(!world.collision(pos.x+delta.x,pos.z))world.rig.position.x+=delta.x;if(!world.collision(pos.x,pos.z+delta.z))world.rig.position.z+=delta.z;}
  if(source.handedness==='right'&&Math.abs(x)>.7&&time-vrLastTurn>450){const before=world.renderer.xr.getCamera().getWorldPosition(new THREE.Vector3());world.rig.rotation.y-=Math.sign(x)*Math.PI/6;world.rig.updateMatrixWorld(true);const after=world.renderer.xr.getCamera().getWorldPosition(new THREE.Vector3());world.rig.position.x+=before.x-after.x;world.rig.position.z+=before.z-after.z;vrLastTurn=time;}}
 renderVRPanel();}

function bindEvents(){
 $('mission-list').addEventListener('click',e=>{const b=e.target.closest('[data-object]');if(b)selectObject(b.dataset.object,true);});$('world-labels').addEventListener('click',e=>{const b=e.target.closest('[data-object]');if(b)selectObject(b.dataset.object,true);});$('room-map').addEventListener('click',e=>{const b=e.target.closest('[data-room]');if(b)loadRoom(+b.dataset.room);});
 document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$('close-inspector').onclick=closeInspector;$('return-explore').onclick=startExplore;$('explore-button').onclick=startExplore;$('submit-project').onclick=finishProject;$('help-button').onclick=help;$('settings-button').onclick=settings;$('map-button').onclick=showProjects;$('close-modal').onclick=closeModal;$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal();});$('vr-button').onclick=enterVR;$('sound-button').onclick=()=>{state.settings.sound=!state.settings.sound;updateSound();sound();save();};$('mobile-missions').onclick=()=>{releasePointer();$('mission-panel').classList.toggle('mobile-open');closeInspector();};$('mobile-interact').onclick=()=>interact();
 $('object-controls').addEventListener('input',e=>{if(e.target.dataset.control)changeValue(e.target.dataset.control,+e.target.value);});$('object-controls').addEventListener('click',e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.dataset.nudge)changeValue(b.dataset.nudge,values()[selected][b.dataset.nudge]+(+b.dataset.delta));if(b.dataset.choice)changeValue(b.dataset.choice,+b.dataset.value);if(b.dataset.layout)changeValue(b.dataset.layout,values()[selected][b.dataset.layout]+(+b.dataset.delta));if(b.dataset.rotate){const rotation=((values()[selected].rotation||0)+45)%360;if(!world.canPlace(selected,{...values()[selected],rotation})){toast('Furnitur tidak bisa diputar karena terhalang. Geser ke area kosong terlebih dahulu.');return;}values()[selected].rotation=rotation;world.update(selected,values()[selected]);$('rotation-value').textContent=values()[selected].rotation+'°';save();}if(b.id==='move-object')beginMove(selected);if(b.id==='reset-object-position')resetObjectPosition();if(b.dataset.cook)cook(b.dataset.cook);if(b.id==='practice-activity')practice();if(b.id==='clean-next'){const i=[0,1,2].find(n=>!values().dirt.cleaned.includes(n));if(i!==undefined)clean(i,true);}});
 $('import-model').onclick=()=>$('model-input').click();$('model-input').onchange=e=>{importModel(e.target.files);e.target.value='';};
 $('objects-button').onclick=showObjects;$('place-object').onclick=placeObject;$('rotate-object').onclick=()=>world.mover.rotate();$('cancel-object').onclick=()=>{world.mover.cancel();toast('Barang kembali ke posisi semula.');};
 $('menu-button').onclick=pauseMenu;$('outdoor-button').onclick=guideDoor;$('neighborhood-button').onclick=guideNeighborhood;$('deliver-carry').onclick=deliverCarry;$('cancel-carry').onclick=cancelCarry;
 for(const input of [$('model-author'),$('model-source')])input.oninput=()=>{const entry=world.objects.get(selected);if(!entry)return;entry.group.userData.credit={author:$('model-author').value.trim(),source:$('model-source').value.trim()};$('model-credit').textContent=($('model-author').value.trim()||'Kreator belum diisi')+' · '+($('model-source').value.trim()||'Sumber belum diisi');};
 $('modal').addEventListener('cancel',event=>{event.preventDefault();closeModal();});
 const canvas=world.renderer.domElement;canvas.tabIndex=0;
 document.addEventListener('pointerlockchange',()=>{const locked=document.pointerLockElement===canvas;document.body.classList.toggle('playing',locked);keys.clear();if(hadPointerLock&&!locked&&!releasingPointer&&!$('modal').open)pauseMenu();hadPointerLock=locked;releasingPointer=false;});document.addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas&&!$('modal').open&&!selected){world.camera.rotation.y-=e.movementX*.002*state.settings.sensitivity;world.camera.rotation.x=clamp(world.camera.rotation.x-e.movementY*.002*state.settings.sensitivity,-1.4,1.4);}});
 canvas.addEventListener('pointerdown',e=>{if(coarse||inputBlocked()||document.pointerLockElement===canvas||drag)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved||=Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>5;world.camera.rotation.y-=dx*.004*state.settings.sensitivity;world.camera.rotation.x=clamp(world.camera.rotation.x-dy*.004*state.settings.sensitivity,-1.4,1.4);drag.x=e.clientX;drag.y=e.clientY;});canvas.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const moved=drag.moved;drag=null;if(!moved){const r=canvas.getBoundingClientRect(),ndc=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),hit=world.pick(ndc);if(hit)interact(hit);else if(!coarse)startExplore();}});canvas.addEventListener('pointercancel',()=>{drag=null;});
 window.addEventListener('keydown',e=>{const editing=e.target.matches('input,select,textarea');if(e.key==='Escape'){e.preventDefault();keys.clear();if($('modal').open)closeModal();else pauseMenu();return;}if(editing||$('modal').open||modalPending||mobile?.portrait||e.ctrlKey||e.altKey||e.metaKey)return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight'].includes(e.code)){e.preventDefault();keys.add(e.code);}if(e.repeat)return;if(e.code==='KeyR'&&world.mover.active){e.preventDefault();world.mover.rotate();}if(e.code==='KeyX'&&world.mover.active){world.mover.cancel();}if(e.code==='KeyF'){e.preventDefault();if(!selected)interact();}if(['Digit1','Digit2','Digit3','Digit4'].includes(e.code))setTool(['inspect','adjust','clean','layout'][+e.code.slice(-1)-1]);if(e.code==='Tab'){e.preventDefault();showProjects();}if(e.code==='KeyH')help();});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();joystick.x=joystick.y=0;drag=null;});document.addEventListener('visibilitychange',()=>{keys.clear();joystick.x=joystick.y=0;});
 mobile=new MobileControls({enabled:coarse,canvas,camera:world.camera,settings:()=>state.settings,joystick,isBlocked:inputBlocked,onReset:()=>{keys.clear();drag=null;},onOrientation:portrait=>{
  if(portrait&&$('modal').open){modalPending=true;$('modal').close();}else if(!portrait&&modalPending){modalPending=false;$('modal').showModal();}
 },onInteract:()=>{const hit=world.pick();if(hit?.id==='dirt'&&!world.carrying)setTool('clean',false);interact(hit);},onMenu:pauseMenu});
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();toast('Grafis terhenti. Progres tersimpan; muat ulang halaman untuk melanjutkan.');});
}
let lastTime=0,frames=0,fpsStart=0,lastLabel=0,previousYaw=null;
function loop(time){
 const dt=Math.min((time-lastTime)/1000||.016,.05);lastTime=time;
 if(!inputBlocked()&&!vrSession){let forward=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)+joystick.y;let strafe=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+joystick.x;const len=Math.hypot(forward,strafe);if(len>1){forward/=len;strafe/=len;}if(len>.01){const before=world.camera.position.clone();world.move(strafe,forward,dt,world.carrying||world.mover.active?1.3:room().id==='outdoor'?(keys.has('ShiftLeft')||keys.has('ShiftRight')||mobile?.sprinting?5.4:3.1):2.1);if(tutorial?.index===0){tutorialDistance+=world.camera.position.distanceTo(before);if(tutorialDistance>.35)tutorial.event('move');}}}
 if(previousYaw!==null&&tutorial?.active&&tutorial.index===1&&!selected&&!$('modal').open){tutorialLook+=Math.abs(world.camera.rotation.y-previousYaw);if(tutorialLook>.15)tutorial.event('look');}previousYaw=world.camera.rotation.y;
 world.tick(dt);tickVR(dt,time);
 if(time-lastLabel>90&&!vrSession){lastLabel=time;focus=world.pick();mobile?.render({hit:focus,moving:world.mover.snapshot(),carrying:world.carrying,distance:world.deliveryDistance(),busy,outdoor:room().id==='outdoor'});$('crosshair').classList.toggle('hot',!!focus);$('focus-prompt').hidden=!focus||!!selected||world.carrying||!!world.mover.active||busy;if(focus){$('focus-name').textContent=focus.id==='gate'?'Gerbang Taman Menteng':focus.id==='exit'?'Pintu ke halaman':focus.id==='entrance'?'Pintu masuk rumah':defFor(focus.id)?.name||'Objek';$('focus-action').textContent=focus.id==='gate'?(world.gate.target?'F · Tutup gerbang':'F · Buka gerbang'):['exit','entrance'].includes(focus.id)?'F · Buka pintu & lanjutkan':focus.id==='dirt'&&tool==='clean'?'Bersihkan area':'Periksa & sesuaikan';}if(!selected)world.highlight(world.carrying||world.mover.active||busy?null:focus?.id);
  if(room().id==='outdoor'){$('neighborhood-location').textContent=world.camera.position.z< -18?'Taman Menteng · kembali ke gerbang':'Ke gerbang · tekan F untuk membuka';}
  const moving=world.mover.active;document.body.classList.toggle('moving-object',!!moving);$('move-hud').hidden=!moving;
  if(moving){$('move-name').textContent=defFor(moving.id)?.name||'Barang';$('move-status').textContent=moving.valid?(coarse?'Tempat tersedia - tekan Letakkan':'Tempat tersedia - F untuk meletakkan'):'Tempat terhalang - cari permukaan kosong';$('place-object').disabled=!moving.valid;}
  $('carry-hud').hidden=!world.carrying;if(world.carrying){const distance=world.deliveryDistance();$('carry-distance').textContent=distance<=1.8?'Sudah dekat · tekan F untuk meletakkan':`Ikuti penanda hijau · meja taman ${distance.toFixed(1)} m`;$('deliver-carry').disabled=distance>1.8;}
  const w=world.container.clientWidth,h=world.container.clientHeight,placed=[];document.querySelectorAll('.world-label').forEach(el=>{const point=world.positionOf(el.dataset.object).project(world.camera);let visible=state.settings.labels&&point.z<1&&point.z> -1&&Math.abs(point.x)<.95&&Math.abs(point.y)<.9&&!document.pointerLockElement;const x=(point.x*.5+.5)*w,baseY=(-point.y*.5+.5)*h-12;let y=baseY;el.style.display=visible?'flex':'none';if(visible){const width=el.offsetWidth||110,height=el.offsetHeight||28;for(let i=0;i<5;i++){const overlapping=placed.find(r=>Math.abs(x-r.x)<(width+r.w)/2+7&&Math.abs(y-r.y)<height+7);if(!overlapping)break;y=overlapping.y-height-8;}if(y<70||(coarse&&x>w-163&&y<160)){el.style.display='none';return;}el.style.left=x+'px';el.style.top=y+'px';el.style.setProperty('--stem',19+baseY-y+'px');placed.push({x,y,w:width});}});
 }
 world.renderer.render(world.scene,world.camera);frames++;if(time-fpsStart>1500){const fps=Math.round(frames*1000/(time-fpsStart));$('fps-indicator').textContent=`${world.low?'ECO':'HD'} · ${fps} FPS`;frames=0;fpsStart=time;}
}
async function init(){try{world=new World($('viewport'),state.settings);tutorial=new Tutorial({onGuide:target=>{closeModal();releasePointer();if(target==='adjust-chair'){selectObject('chair',true);return;}closeInspector();if(target==='dirt'){setTool('clean',false);const i=[0,1,2].find(n=>!values().dirt.cleaned.includes(n));if(i===undefined){tutorial.event('clean');return;}world.objects.get('dirt').group=world.dirts[i];}world.focus(target);},onFinish:completed=>{state.onboarding={completed:completed||state.onboarding.completed,skipped:!completed};state.settings.tutorialCompleted=state.onboarding.completed;save();toast(completed?'Tutorial selesai. Sekarang jelajahi dan perbaiki ruang dengan cara Anda sendiri.':'Tutorial diakhiri. Anda bisa mengulangnya lewat menu Esc.');}});bindEvents();setupVR();updateSound();loadRoom(state.current);world.renderer.setAnimationLoop(loop);await world.hands.ready;await world.renderer.compileAsync(world.scene,world.camera);$('loading').style.opacity='0';setTimeout(()=>{$('loading').hidden=true;if(!state.onboarding.completed&&!state.onboarding.skipped)welcome();},600);document.documentElement.dataset.ready='true';}catch(error){console.error(error);$('loading-text').textContent='Grafis 3D belum dapat dimuat. Gunakan browser dengan WebGL 2 aktif, lalu muat ulang.';$('loading').querySelector('.loading-track').hidden=true;}}
window.addEventListener('beforeunload',()=>{try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));}catch{}});
// Read-only telemetry for browser verification and local performance inspection.
window.ergoDebug={snapshot:()=>({room:room().id,selected,tool,score:result?.score,done:result?.done,canComplete:result?.canComplete,state:structuredClone(state),camera:world?.camera.position.toArray(),rotation:world?.camera.rotation.toArray(),assets:structuredClone(world?.assetState),drawCalls:world?.renderer.info.render.calls,triangles:world?.renderer.info.render.triangles,xr:!!vrSession,moving:world?.mover.snapshot(),props:[...world.objects.keys()].filter(id=>!['dirt','gate','exit','entrance'].includes(id)),hands:world?.hands.snapshot(),touch:{portrait:!!mobile?.portrait,joystick:{...joystick},sprinting:!!mobile?.sprinting},neighborhood:room().id==='outdoor'?{bounds:{...world.bounds},residences:structuredClone(world.residences),gateOpen:world.gate?.target===1,gateProgress:world.gate?.progress}:null,carrying:!!world?.carrying,deliveryDistance:room().id==='outdoor'?world?.deliveryDistance():null,deliveryTarget:world?.deliveryTarget?.toArray(),tutorial:{active:tutorial?.active,index:tutorial?.index,passed:tutorial?.passed}}),treeBases:()=>world.treeBases(),objectBounds:id=>world.objectBounds(id),projectObject:id=>{const p=world.positionOf(id).project(world.camera),rect=world.renderer.domElement.getBoundingClientRect();return {x:rect.left+(p.x*.5+.5)*rect.width,y:rect.top+(-p.y*.5+.5)*rect.height,z:p.z};}};
init();
